name: Rodar DOU Bot

on:
  schedule:
    - cron: '0 13 * * *'  # 10h Brasil
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libpango-1.0-0 \
            libpangoft2-1.0-0 \
            libharfbuzz0b \
            libffi-dev \
            libcairo2
      
      - name: Instalar dependências Python
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Rodar script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python main.py
